### ISSUE TITLE
Battleship_server

### ISSUE THREAD

**Issue by FabrizioVx** [rrivas-utec/battleship_server#1]

**Comment by jneirar** [comment]
No permite posicionar en la columna J, solo está permitido desde A-I.
No genera mensaje FULL cuando toda la flota es ingresada.

**Comment by rrivas-utec** [comment]
> 
> 
> No permite posicionar en la columna J, solo está permitido desde A-I.
> No genera mensaje FULL cuando toda la flota es ingresada.

Estimado Jorge, los issues han sido corregidos, ¿Podrias verificarlo?
